### ISSUE TITLE
Subtitles support?

### ISSUE THREAD

**Issue by erral** [joerns/xbmc-plugin.video.tagesschau#10]
Hi:

I see that there is a 'subtitles.py' file in this addon, but what do I need to do to enable it?

Vielen Dank!

**Comment by mablae** [comment]
Hey, these code parts are not in use by the main script yet. 

Maybe it was just an experiement of @joerns

**Comment by erral** [comment]
Hi again:

It looks like I had subtitles disabled or something... I enabled subtitles for German and today I see both the archived tagesshau and tagestheme with subtitles.

Danke!!

**Comment by mablae** [comment]
Sounds awsome, but these code parts are not used for that. Maybe the streams contain the subtitles directly so there was no need to use the above module anymore. @joerns is that correct?

**Comment by joerns** [comment]
Hi,

in fact the subtitles.py *is* used in the main script. That code was contributed by @henningSaul. 

Anyway, I am glad it works now!
Cheers, Jörn
