### ISSUE TITLE
Disable subtitles in config-menu

### ISSUE THREAD

**Issue by EifX** [joerns/xbmc-plugin.video.tagesschau#13]
Hey there,

first of all: I like your addon! Very good work :+1:

I have a little enhancement for this plugin. It's possible to add a config-option to disable subtitles generally?

Now, if I look a video, I disable the subtitles at every video during play.

**Comment by joerns** [comment]
Hi,

that is possible, but I am not doing any active development anymore. If you or a volunteer contributes the code, I am happy to merge it.
