### ISSUE TITLE
Tagesschau in 100 Sekunden

### ISSUE THREAD

**Issue by daenny** [joerns/xbmc-plugin.video.tagesschau#8]
Hallo,
Ich bin ein grosser Fan des plug ins, Aber seit ein paar Versionen kann ich jetzt die Tagesschau in 100 Sekungen nicht mehr finden. Die Sendung taucht im:
http://www.tagesschau.de/api/multimedia/video/ondemand100~_type-video.json
Feed noch auf. Ich habe mir den Code jetzt noch nicht ganz genau angeguckt, aber ist da irgendein Filter, sodass man das wieder einfach aktivieren kann?
Danke und viele Gruesse,
Daniel

**Comment by joerns** [comment]
Hi,

danke fuers Reporten. Einen einfachen Filter gibt es nicht. Es klingt nach
einem Bug, moeglicherweise hat sich etwas an der Struktur des RSS Feeds
geaendert. Ich schau mir das bei Gelegenheit an, solltest du den Fehler im
Code in der Zwischenzeit finden waere es gut wenn du das hier postest.

Danke und Ciao,
 Joern

2015-01-16 23:12 GMT+01:00 Daniel Claes <notifications@github.com>:

**Comment by daenny** [comment]
Ja es scheint jetzt unter "Livestreams" als eigenes JSON item zu sein. Ich habe jetzt mal einen "Hack" geschrieben, der die Tagesschau in 100 Sekunden unter Letzte Videos hinzufuegt. Das ist noch nicht ideal, aber so wird es zumindest angezeigt ;)
http://pastebin.com/bbPxNjPu

**Comment by mablae** [comment]
We not creating PR of that? :+1:  :smile:

**Comment by daenny** [comment]
Here you go. It is kind of a "hack" as described above:
https://github.com/joerns/xbmc-plugin.video.tagesschau/pull/9
